{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Проверка, что система вернула ошибку", "status": "passed", "start": 1727348971026, "stop": 1727348971026}], "attachments": [{"name": "stdout", "source": "d7f803f3-1c39-4d46-8ac1-469fe1e48697-attachment.txt", "type": "text/plain"}], "start": 1727348969880, "stop": 1727348971028, "uuid": "c69825c6-a0e0-4320-8e5c-7878433c1ec3", "historyId": "4b8f7121f2677ec2ae18b5989c1e8f88", "testCaseId": "4b8f7121f2677ec2ae18b5989c1e8f88", "fullName": "test.test_courier_login#test_login_with_invalid_credentials", "labels": [{"name": "feature", "value": "Авторизиция с невалидними данными"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "Liana_M"}, {"name": "thread", "value": "3400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_courier_login"}]}