{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Проверка, что система вернула ошибку", "status": "passed", "start": 1727187323962, "stop": 1727187323962}], "attachments": [{"name": "stdout", "source": "6fb91ccc-10dd-4bb7-b772-bc2378814f70-attachment.txt", "type": "text/plain"}], "start": 1727187322831, "stop": 1727187323965, "uuid": "a6b1664e-3a77-48ac-a97e-8461d9b225d1", "historyId": "4b8f7121f2677ec2ae18b5989c1e8f88", "testCaseId": "4b8f7121f2677ec2ae18b5989c1e8f88", "fullName": "test.test_courier_login#test_login_with_invalid_credentials", "labels": [{"name": "feature", "value": "Авторизиция с невалидними данными"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "Liana_M"}, {"name": "thread", "value": "9068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_courier_login"}]}